### ISSUE TITLE
In zlibwapi_143.vcxproj, lines referencing zlib128 are wrong.

### ISSUE THREAD

**Issue by hackwrench** [ansani/Shareaza#110]
The paths start out 'projects\' and should start out '..\vc143\projects\'
Compare with shareaza_143.vcxproj which references boost files and has the paths set right.
[zlibwapi_143.zip](https://github.com/ansani/Shareaza/files/10670575/zlibwapi_143.zip)
Attached zip file is apparently still problematic but compiles. Zlib128 doesn.t show up in the NuGet Manager though.

**Comment by hackwrench** [comment]
Relaunched Visual Studio and Zlib128 showed up in NuGet Package Manager

**Comment by ansani** [comment]
I cannot reproduce the issue. I loaded the project on different VC setups on other PCs, and I could build the solution without any problems.
