### ISSUE TITLE
Virustotal detects the .exe installer as a virus

### ISSUE THREAD

**Issue by ansani** [ansani/Shareaza#138]

**Comment by donttrustansani** [comment]
Never trust Salvatore Ansani, he is a cracker, he was arrested, he spies and he uses trojans and other malware: https://www-corrieredellacalabria-it.translate.goog/2019/05/22/hacker-di-stato-arrestato-il-calabrese-amministratore-di-e-surv/

**Comment by ansani** [comment]
I created an automated action in GitHub to automatically submit a new release to VT and report the result. You can check everything in the GH Action workflow for every specific release.
