### ISSUE TITLE
It should be possible to sort downloads by added date (with a sorely missing “Added date” column)

### ISSUE THREAD

**Issue by abolibibelot1980** [ansani/Shareaza#87]
With eMule it's easy to temporarily sort downloads any way you like, either by name, size, added date, “last seen” date, current transfer speed, status, you name it... and then go back to your favorite kind of sorting in a split second. With Shareaza, I always dread accidentally clicking on any column name in the “Transfers” area, as it will mess with the sorting permanently, with no way of recovering the former sorting, or at least any kind of meaningful sorting, since it doesn't even have an “Added date” column (or “Time added”, whatever the name might be), which would seem like an extremely basic feature for any downloading utility. (In fact I can't think of another one which is lacking this.) Or if there is one somewhere, forgive me ’cause I never found it — I did find a “Time” column in search tabs, or I did accidentally find a well-hidden “Time” column in user browsing tabs, which appears only when clicking on a certain spot with a single-pixel accuracy to slide the “Title” column to the right, how convenient is that... that “Time” column doesn't appear in the list shown when right-clicking on any of the columns' names, only the “extra” available columns appear here, those which can be defined according to specific schemes — and none of that appears at all in the “Transfers” area, where only three menu items are shown : “Help”, “Clear completed”, “Auto clear”. There should be an extra item to select columns to add (and “Added date” / “Time added” is definitely the most egregious oversight here) or remove (“Country” for instance is barely relevant in the “Transfers” area, whereas it can certainly be useful to sort search results).

Likewise, I didn't find any way to do a search within the download queue, as eMule allows, either with a small search menu accessible through a right-click menu item or through CTRL+F, or even quicker by typing the first few characters of the download's name. There is a “filter” button, but then again, as per the issue described above, I haven't even tested it as I dread modifying the currently displayed list in any way as I have no way of retrieving the former sorting if it ends up messed up as a result. (It happened that the queue sorting was completely messed up after a BSOD, I was really pissed, but at least I found out that it was caused by a corruption of the "DownloadGroups.dat" file, and since I do regular backups of Shareaza's AppData directory I could recover the former sorting, except for downloads which were added after the backup. But this wouldn't be necessary if sorting features in Shareaza weren't so crippled to begin with.)

**Comment by ansani** [comment]
The goal is to add a new column "Added Date" referring to the download itself. To accomplish the task, the **DOWNLOAD_SER_VERSION** must be upgraded to **44** (current version is 43).
